name: 'Add to changelog'
description: 'Prepends text to the changelog'
inputs:
  version:
    description: The version to add to the changelog
    required: true
  body:
    description: Content to be appended to the changelog
    required: true
  pr-url:
    description: The url to the pull request
    required: true
  changelog-path:
    description: The relative path to the changelog file
    required: false
    default: 'CHANGELOG.md'

runs:
  using: 'node12'
  main: 'release/index.js'
